spring:
  application:
    name: welcome-service    
  config:
    import: optional:configserver:http://localhost:9093
    
management:
  endpoints:
    web:
      exposure:
        include: refresh
        
   
